<?php

namespace App\Filament\Resources;

use App\Filament\Resources\TurnResource\Pages;
use App\Filament\Resources\TurnResource\RelationManagers;
use App\Models\Turn;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Notifications\Actions\Action;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class TurnResource extends Resource
{
    protected static ?string $model = Turn::class;
    protected static ?string $label='رزرو';
    protected static ?string $pluralLabel='رزروها';


    protected static ?string $navigationIcon = 'heroicon-o-clock';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')->label('نام و نام خانوادگی')->required()->maxLength(255),
                Forms\Components\TextInput::make('phone_number')->prefixIcon('heroicon-s-device-phone-mobile')->prefixIconColor('icon')->label('شماره تلفن')->tel()->required()->maxLength(11),
                Forms\Components\DatePicker::make('date')->label('تاریخ رزرو')->required()->jalali()->closeOnDateSelection(),
                Forms\Components\TimePicker::make('time')->label('ساعت رزرو')->jalali()->required()->withoutSeconds(),
                Forms\Components\Select::make('count')->label('تعداد')->columnSpanFull()->required()->options([1=>1,2=>2,3=>3,4=>4,5=>5,6=>6,7=>7,8=>8,'more'=>'بیشتر'])->searchable(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')->label('نام ونام خانوادگی')->searchable()->alignCenter(),
                Tables\Columns\TextColumn::make('phone_number')->label('شماره تلفن')->searchable()->alignCenter(),
                Tables\Columns\TextColumn::make('date')->label('تاریخ رزرو')->jalaliDate()->sortable()->alignCenter(),
                Tables\Columns\TextColumn::make('time')->time('H:i')->label('ساعت رزرو')->alignCenter(),
                Tables\Columns\TextColumn::make('count')->badge()->label('تعداد')->sortable()->alignCenter(),
                Tables\Columns\TextColumn::make('created_at')->jalaliDate()->sortable()->alignCenter()->label('تاریخ درخواست'),
                Tables\Columns\TextColumn::make('read_at')->jalaliDate()->alignCenter()->sortable()->label('تاریخ برسی'),
                Tables\Columns\TextColumn::make('result')->tooltip(fn($record)=>$record->result)->alignCenter()->sortable()->label('نتیجه'),

            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\Action::make('answer')->label('پاسخ')->form([
                    Forms\Components\Textarea::make('result')->label('نتیجه درخواست')->required(),
                ])->action(function ($data,$record){
                    $record->update([
                        'result'=>$data['result'],
                        'read_at'=>now()
                    ]);
                    Notification::make('success')->title('پاسخ رزرو شما ثبت شد')->actions([
                        Action::make('link')->label(' رزرو')->url(TurnResource::getUrl('index',['tableSearch'=>$record->name]))->color('a')
                    ])->success()->color('success')->send()->sendToDatabase(users: auth()->user());
                })->requiresConfirmation()
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }
    public static function getNavigationBadge(): ?string
    {
        return Turn::query()->where('read_at',null)->count(); // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListTurns::route('/'),
            'create' => Pages\CreateTurn::route('/create'),
            'edit' => Pages\EditTurn::route('/{record}/edit'),
        ];
    }
}
